### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by jarad** [wlandau/fbseqOpenMP#3]
g++ -m64 -I/usr/include/R -DNDEBUG  -I/usr/local/include   -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c fbseqOpenMP.cpp -o fbseqOpenMP.o
In file included from fbseqOpenMP.cpp:20:0:
sampler/targets.h: In function ‘double ltarget_nu(chain_t_, args_t, double)’:
sampler/targets.h:47:8: warning: suggest parentheses around comparison in operand of ‘&’ [-Wparentheses]
   if(x > args.lowerbound & x < args.D)
        ^
In file included from /usr/include/R/R.h:31:0,
                 from util/include.h:4,
                 from fbseqOpenMP.cpp:1:
sampler/slice_horseshoe.h: In function ‘args_t slice_horseshoe(chain_t_, args_t)’:
sampler/slice_horseshoe.h:26:12: error: expected unqualified-id before ‘(’ token
   if(!std::isfinite(args.x)) args.x = args.x0;
            ^
make: **\* [fbseqOpenMP.o] Error 1
ERROR: compilation failed for package ‘fbseqOpenMP’
- removing ‘/home/niemi/R/x86_64-redhat-linux-gnu-library/3.2/fbseqOpenMP’
  Error: Command failed (1)

**Comment by wlandau** [comment]
There was a problem with `std::isfinite` and `R` version < 3.3.0. I have reproduced and the error on `R` 3.2.3 and fixed it for `R` 3.2.3, 3.3.0, and 3.3.1. I have also added `R` >= 3.2.3 as a dependency in the `DESCRIPTION`.

**Comment by jarad** [comment]
Confirmed that this fixed the error for me.

**Comment by wlandau** [comment]
Thanks for checking, Jarad.
